### ISSUE TITLE
Sorry, not an issue but config question

### ISSUE THREAD

**Issue by JamieP83** [dshokouhi/Home-AssistantConfig#4]
Hey!
thanks for everything on Neato, its awesome :)

I had a question, sorry if this is not the correct place - where would be if so?

im using the zone cleaning to do rooms in the house, which works REALLY well.
however im trying to have a script that does multiple rooms in one command, eg. bathroom and hallway.
how would i add multiple "zones" to a command?
this doesnt seem to work or is it impossible?

```
vacuum_all_downstairs:
  alias: "Vacuum All Downstairs"
  sequence:
    - service: vacuum.neato_custom_cleaning
      data:
        entity_id: vacuum.rover
        mode: 2 #Set the cleaning mode: 1 for eco and 2 for turbo. Defaults to turbo if not set
        navigation: 3 #1 for normal, 2 for extra care, 3 for deep
        #category: #Whether to use a persistent map or not for cleaning (i.e. No go lines): 2 for no map, 4 for map. Default to using map if not set (and fallback to no map if no map is found).
        zone: "Kitchen and Dining Room", "Living Room", "Office", "Hallway", "Bar"
```
